import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Container, CssBaseline, Toolbar } from "@mui/material";
import Header from "@/components/layout/Header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <CssBaseline />
        <Header />
        <Toolbar />
        <Container
          component="main"
          sx={{ py: 2 }}
        >
          {children}
        </Container>
      </body>
    </html>
  );
}
