name: docker-example action
on:
  push:
    branches: [feature/docker-example]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: "module_10/docker-example"
          sparse-checkout-cone-mode: false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./module_10/docker-example
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-example:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
